
version: '3.8'

services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crawl
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
