// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvyleuiwbmbpfpmrstgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2eWxldWl3Ym1icGZwbXJzdGdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NTE2ODUsImV4cCI6MjA2MTQyNzY4NX0.t94gWlw1hL-Y6B3MED3ovc_Ibm8NvGrQB2HO8_rOfS4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);